package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"street/domain"
)

var allCommands = []string{
	domain.AdminAccessLogsAction,
	domain.AdminDashboardAction,
	domain.AdminFilesAction,
	domain.AdminPropHistoriesAction,
	domain.AdminPropertiesAction,
	domain.AdminUsersAction,
	domain.GuestAutoLoginAction,
	domain.GuestDebugAction,
	domain.GuestExternalAuthAction,
	domain.GuestFilesAction,
	domain.GuestForgotPasswordAction,
	domain.GuestLoginAction,
	domain.GuestOauthCallbackAction,
	domain.GuestPropertyAction,
	domain.GuestRegisterAction,
	domain.GuestResendVerificationEmailAction,
	domain.GuestResetPasswordAction,
	domain.GuestVerifyEmailAction,
	domain.RealtorOwnedPropertiesAction,
	domain.RealtorPropertyAction,
	domain.RealtorUpsertPropertyAction,
	domain.UserAutoLoginLinkAction,
	domain.UserChangePasswordAction,
	domain.UserDeactivateAction,
	domain.UserLikePropAction,
	domain.UserLogoutAction,
	domain.UserNearbyFacilitiesAction,
	domain.UserProfileAction,
	domain.UserPropHistoryAction,
	domain.UserSearchPropAction,
	domain.UserSessionKillAction,
	domain.UserSessionsActiveAction,
	domain.UserUpdateProfileAction,
	domain.UserUploadFileAction,
}

// Code generated by 1_codegen_test.go DO NOT EDIT.
