package presentation

// Code generated by 1_codegen_test.go DO NOT EDIT.

import (
	"street/domain"
)

var allCommands = []string{
	domain.GuestForgotPasswordAction,
	domain.GuestLoginAction,
	domain.GuestRegisterAction,
	domain.GuestResendVerificationEmailAction,
	domain.GuestResetPasswordAction,
	domain.GuestVerifyEmailAction,
	domain.UserLogoutAction,
	domain.UserProfileAction,
}

// Code generated by 1_codegen_test.go DO NOT EDIT.
