package presentation

import (
	"github.com/gofiber/fiber/v2"
	"github.com/kokizzu/gotro/M"
)


// Code generated by 1_codegen_test.go DO NOT EDIT.


var viewList = map[string]string{
	`Admin`: `../svelte/admin.html`, // ../svelte/admin.svelte
	`AdminActionLogs`: `../svelte/admin/actionLogs.html`, // ../svelte/admin/actionLogs.svelte
	`AdminSessions`: `../svelte/admin/sessions.html`, // ../svelte/admin/sessions.svelte
	`AdminUsers`: `../svelte/admin/users.html`, // ../svelte/admin/users.svelte
	`Buyer`: `../svelte/buyer.html`, // ../svelte/buyer.svelte
	`Error`: `../svelte/error.html`, // ../svelte/error.svelte
	`GuestOauthCallback`: `../svelte/guest/oauthCallback.html`, // ../svelte/guest/oauthCallback.svelte
	`GuestResetPassword`: `../svelte/guest/resetPassword.html`, // ../svelte/guest/resetPassword.svelte
	`GuestVerifyEmail`: `../svelte/guest/verifyEmail.html`, // ../svelte/guest/verifyEmail.svelte
	`Index`: `../svelte/index.html`, // ../svelte/index.svelte
	`NodeModulesSvelteLightweightChartsComponentsAreaSeries`: `../svelte/node_modules/svelte-lightweight-charts/components/area-series.html`, // ../svelte/node_modules/svelte-lightweight-charts/components/area-series.svelte
	`NodeModulesSvelteLightweightChartsComponentsBarSeries`: `../svelte/node_modules/svelte-lightweight-charts/components/bar-series.html`, // ../svelte/node_modules/svelte-lightweight-charts/components/bar-series.svelte
	`NodeModulesSvelteLightweightChartsComponentsBaselineSeries`: `../svelte/node_modules/svelte-lightweight-charts/components/baseline-series.html`, // ../svelte/node_modules/svelte-lightweight-charts/components/baseline-series.svelte
	`NodeModulesSvelteLightweightChartsComponentsCandlestickSeries`: `../svelte/node_modules/svelte-lightweight-charts/components/candlestick-series.html`, // ../svelte/node_modules/svelte-lightweight-charts/components/candlestick-series.svelte
	`NodeModulesSvelteLightweightChartsComponentsChart`: `../svelte/node_modules/svelte-lightweight-charts/components/chart.html`, // ../svelte/node_modules/svelte-lightweight-charts/components/chart.svelte
	`NodeModulesSvelteLightweightChartsComponentsHistogramSeries`: `../svelte/node_modules/svelte-lightweight-charts/components/histogram-series.html`, // ../svelte/node_modules/svelte-lightweight-charts/components/histogram-series.svelte
	`NodeModulesSvelteLightweightChartsComponentsInternalContextProvider`: `../svelte/node_modules/svelte-lightweight-charts/components/internal/context-provider.html`, // ../svelte/node_modules/svelte-lightweight-charts/components/internal/context-provider.svelte
	`NodeModulesSvelteLightweightChartsComponentsLineSeries`: `../svelte/node_modules/svelte-lightweight-charts/components/line-series.html`, // ../svelte/node_modules/svelte-lightweight-charts/components/line-series.svelte
	`NodeModulesSvelteLightweightChartsComponentsPriceLine`: `../svelte/node_modules/svelte-lightweight-charts/components/price-line.html`, // ../svelte/node_modules/svelte-lightweight-charts/components/price-line.svelte
	`NodeModulesSvelteLightweightChartsComponentsPriceScale`: `../svelte/node_modules/svelte-lightweight-charts/components/price-scale.html`, // ../svelte/node_modules/svelte-lightweight-charts/components/price-scale.svelte
	`NodeModulesSvelteLightweightChartsComponentsTimeScale`: `../svelte/node_modules/svelte-lightweight-charts/components/time-scale.html`, // ../svelte/node_modules/svelte-lightweight-charts/components/time-scale.svelte
	`Privacy`: `../svelte/privacy.html`, // ../svelte/privacy.svelte
	`Realtor`: `../svelte/realtor.html`, // ../svelte/realtor.svelte
	`Tos`: `../svelte/tos.html`, // ../svelte/tos.svelte
	`User`: `../svelte/user.html`, // ../svelte/user.svelte
}


func (v *Views) RenderAdmin(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`Admin`].Str(m))
}

func (v *Views) RenderAdminActionLogs(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`AdminActionLogs`].Str(m))
}

func (v *Views) RenderAdminSessions(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`AdminSessions`].Str(m))
}

func (v *Views) RenderAdminUsers(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`AdminUsers`].Str(m))
}

func (v *Views) RenderBuyer(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`Buyer`].Str(m))
}

func (v *Views) RenderError(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`Error`].Str(m))
}

func (v *Views) RenderGuestOauthCallback(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`GuestOauthCallback`].Str(m))
}

func (v *Views) RenderGuestResetPassword(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`GuestResetPassword`].Str(m))
}

func (v *Views) RenderGuestVerifyEmail(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`GuestVerifyEmail`].Str(m))
}

func (v *Views) RenderIndex(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`Index`].Str(m))
}

func (v *Views) RenderNodeModulesSvelteLightweightChartsComponentsAreaSeries(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`NodeModulesSvelteLightweightChartsComponentsAreaSeries`].Str(m))
}

func (v *Views) RenderNodeModulesSvelteLightweightChartsComponentsBarSeries(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`NodeModulesSvelteLightweightChartsComponentsBarSeries`].Str(m))
}

func (v *Views) RenderNodeModulesSvelteLightweightChartsComponentsBaselineSeries(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`NodeModulesSvelteLightweightChartsComponentsBaselineSeries`].Str(m))
}

func (v *Views) RenderNodeModulesSvelteLightweightChartsComponentsCandlestickSeries(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`NodeModulesSvelteLightweightChartsComponentsCandlestickSeries`].Str(m))
}

func (v *Views) RenderNodeModulesSvelteLightweightChartsComponentsChart(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`NodeModulesSvelteLightweightChartsComponentsChart`].Str(m))
}

func (v *Views) RenderNodeModulesSvelteLightweightChartsComponentsHistogramSeries(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`NodeModulesSvelteLightweightChartsComponentsHistogramSeries`].Str(m))
}

func (v *Views) RenderNodeModulesSvelteLightweightChartsComponentsInternalContextProvider(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`NodeModulesSvelteLightweightChartsComponentsInternalContextProvider`].Str(m))
}

func (v *Views) RenderNodeModulesSvelteLightweightChartsComponentsLineSeries(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`NodeModulesSvelteLightweightChartsComponentsLineSeries`].Str(m))
}

func (v *Views) RenderNodeModulesSvelteLightweightChartsComponentsPriceLine(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`NodeModulesSvelteLightweightChartsComponentsPriceLine`].Str(m))
}

func (v *Views) RenderNodeModulesSvelteLightweightChartsComponentsPriceScale(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`NodeModulesSvelteLightweightChartsComponentsPriceScale`].Str(m))
}

func (v *Views) RenderNodeModulesSvelteLightweightChartsComponentsTimeScale(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`NodeModulesSvelteLightweightChartsComponentsTimeScale`].Str(m))
}

func (v *Views) RenderPrivacy(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`Privacy`].Str(m))
}

func (v *Views) RenderRealtor(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`Realtor`].Str(m))
}

func (v *Views) RenderTos(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`Tos`].Str(m))
}

func (v *Views) RenderUser(c *fiber.Ctx, m M.SX) error {
	c.Set("Content-Type", "text/html")
	return c.SendString(v.cache[`User`].Str(m))
}

// Code generated by 1_codegen_test.go DO NOT EDIT.
