
import axios from "axios";

// Code generated by 1_codegen_test.go DO NOT EDIT.
/**
 * @typedef {Object} DecryptIn
 */
const DecryptIn = {
}
/**
 * @typedef {Object} DecryptOut
 */
const DecryptOut = {
}
/**
 * @callback DecryptCallback
 * @param {bool} o
 * @returns {Promise}
 */
/**
 * @param  {string} i
 * @param {DecryptCallback} cb
 * @returns {Promise}
 */
async function Decrypt( i, cb ) {
  return await axios.post( '/', i ).then( cb )
}

/**
 * @typedef {Object} EncryptIn
 */
const EncryptIn = {
}
/**
 * @typedef {Object} EncryptOut
 */
const EncryptOut = {
}
/**
 * @callback EncryptCallback
 * @param {string} o
 * @returns {Promise}
 */
/**
 * @param  {string} i
 * @param {EncryptCallback} cb
 * @returns {Promise}
 */
async function Encrypt( i, cb ) {
  return await axios.post( '/', i ).then( cb )
}

/**
 * @typedef {Object} GuestForgotPasswordIn
 * @property {String} Email
 */
const GuestForgotPasswordIn = {
  Email: '', // string
}
/**
 * @typedef {Object} GuestForgotPasswordOut
 * @property {Object} Ok
 * @property {String} resetPassUrl
 */
const GuestForgotPasswordOut = {
  Ok: { // bool
  }, // bool
  resetPassUrl: '', // string
}
/**
 * @callback GuestForgotPasswordCallback
 * @param {GuestForgotPasswordOut} o
 * @returns {Promise}
 */
/**
 * @param  {GuestForgotPasswordIn} i
 * @param {GuestForgotPasswordCallback} cb
 * @returns {Promise}
 */
async function GuestForgotPassword( i, cb ) {
  return await axios.post( '/guest/forgotPassword', i ).then( cb )
}

/**
 * @typedef {Object} GuestLoginIn
 * @property {String} Email
 * @property {String} Password
 */
const GuestLoginIn = {
  Email: '', // string
  Password: '', // string
}
/**
 * @typedef {Object} GuestLoginOut
 * @property {number} User.Id
 * @property {String} User.Email
 * @property {String} User.Password
 * @property {number} User.CreatedAt
 * @property {number} User.CreatedBy
 * @property {number} User.UpdatedAt
 * @property {number} User.UpdatedBy
 * @property {number} User.DeletedAt
 * @property {number} User.PasswordSetAt
 * @property {String} User.SecretCode
 * @property {number} User.SecretCodeAt
 * @property {number} User.VerificationSentAt
 * @property {number} User.VerifiedAt
 * @property {number} User.LastLoginAt
 */
const GuestLoginOut = {
  User: { // rqAuth.Users
    Id: 0, // uint64
    Email: '', // string
    Password: '', // string
    CreatedAt: 0, // int64
    CreatedBy: 0, // uint64
    UpdatedAt: 0, // int64
    UpdatedBy: 0, // uint64
    DeletedAt: 0, // int64
    PasswordSetAt: 0, // int64
    SecretCode: '', // string
    SecretCodeAt: 0, // int64
    VerificationSentAt: 0, // int64
    VerifiedAt: 0, // int64
    LastLoginAt: 0, // int64
  }, // rqAuth.Users
}
/**
 * @callback GuestLoginCallback
 * @param {GuestLoginOut} o
 * @returns {Promise}
 */
/**
 * @param  {GuestLoginIn} i
 * @param {GuestLoginCallback} cb
 * @returns {Promise}
 */
async function GuestLogin( i, cb ) {
  return await axios.post( '/guest/login', i ).then( cb )
}

/**
 * @typedef {Object} GuestRegisterIn
 * @property {String} Email
 * @property {String} Password
 */
const GuestRegisterIn = {
  Email: '', // string
  Password: '', // string
}
/**
 * @typedef {Object} GuestRegisterOut
 * @property {number} User.Id
 * @property {String} User.Email
 * @property {String} User.Password
 * @property {number} User.CreatedAt
 * @property {number} User.CreatedBy
 * @property {number} User.UpdatedAt
 * @property {number} User.UpdatedBy
 * @property {number} User.DeletedAt
 * @property {number} User.PasswordSetAt
 * @property {String} User.SecretCode
 * @property {number} User.SecretCodeAt
 * @property {number} User.VerificationSentAt
 * @property {number} User.VerifiedAt
 * @property {number} User.LastLoginAt
 */
const GuestRegisterOut = {
  User: { // rqAuth.Users
    Id: 0, // uint64
    Email: '', // string
    Password: '', // string
    CreatedAt: 0, // int64
    CreatedBy: 0, // uint64
    UpdatedAt: 0, // int64
    UpdatedBy: 0, // uint64
    DeletedAt: 0, // int64
    PasswordSetAt: 0, // int64
    SecretCode: '', // string
    SecretCodeAt: 0, // int64
    VerificationSentAt: 0, // int64
    VerifiedAt: 0, // int64
    LastLoginAt: 0, // int64
  }, // rqAuth.Users
}
/**
 * @callback GuestRegisterCallback
 * @param {GuestRegisterOut} o
 * @returns {Promise}
 */
/**
 * @param  {GuestRegisterIn} i
 * @param {GuestRegisterCallback} cb
 * @returns {Promise}
 */
async function GuestRegister( i, cb ) {
  return await axios.post( '/guest/register', i ).then( cb )
}

/**
 * @typedef {Object} GuestResetPasswordIn
 * @property {String} SecretCode
 * @property {String} Hash
 * @property {String} Password
 */
const GuestResetPasswordIn = {
  SecretCode: '', // string
  Hash: '', // string
  Password: '', // string
}
/**
 * @typedef {Object} GuestResetPasswordOut
 * @property {Object} Ok
 */
const GuestResetPasswordOut = {
  Ok: { // bool
  }, // bool
}
/**
 * @callback GuestResetPasswordCallback
 * @param {GuestResetPasswordOut} o
 * @returns {Promise}
 */
/**
 * @param  {GuestResetPasswordIn} i
 * @param {GuestResetPasswordCallback} cb
 * @returns {Promise}
 */
async function GuestResetPassword( i, cb ) {
  return await axios.post( '/guest/resetPassword', i ).then( cb )
}

/**
 * @typedef {Object} MarshalEnkodoIn
 */
const MarshalEnkodoIn = {
}
/**
 * @typedef {Object} MarshalEnkodoOut
 */
const MarshalEnkodoOut = {
}
/**
 * @callback MarshalEnkodoCallback
 * @param {error} o
 * @returns {Promise}
 */
/**
 * @param  {enkodo.Encoder} i
 * @param {MarshalEnkodoCallback} cb
 * @returns {Promise}
 */
async function MarshalEnkodo( i, cb ) {
  return await axios.post( '/', i ).then( cb )
}

/**
 * @typedef {Object} UnmarshalEnkodoIn
 */
const UnmarshalEnkodoIn = {
}
/**
 * @typedef {Object} UnmarshalEnkodoOut
 */
const UnmarshalEnkodoOut = {
}
/**
 * @callback UnmarshalEnkodoCallback
 * @param {error} o
 * @returns {Promise}
 */
/**
 * @param  {enkodo.Decoder} i
 * @param {UnmarshalEnkodoCallback} cb
 * @returns {Promise}
 */
async function UnmarshalEnkodo( i, cb ) {
  return await axios.post( '/', i ).then( cb )
}

/**
 * @typedef {Object} UserLogoutIn
 */
const UserLogoutIn = {
}
/**
 * @typedef {Object} UserLogoutOut
 * @property {number} LogoutAt
 */
const UserLogoutOut = {
  LogoutAt: 0, // int64
}
/**
 * @callback UserLogoutCallback
 * @param {UserLogoutOut} o
 * @returns {Promise}
 */
/**
 * @param  {UserLogoutIn} i
 * @param {UserLogoutCallback} cb
 * @returns {Promise}
 */
async function UserLogout( i, cb ) {
  return await axios.post( '/', i ).then( cb )
}

/**
 * @typedef {Object} UserProfileIn
 */
const UserProfileIn = {
}
/**
 * @typedef {Object} UserProfileOut
 * @property {number} User.Id
 * @property {String} User.Email
 * @property {String} User.Password
 * @property {number} User.CreatedAt
 * @property {number} User.CreatedBy
 * @property {number} User.UpdatedAt
 * @property {number} User.UpdatedBy
 * @property {number} User.DeletedAt
 * @property {number} User.PasswordSetAt
 * @property {String} User.SecretCode
 * @property {number} User.SecretCodeAt
 * @property {number} User.VerificationSentAt
 * @property {number} User.VerifiedAt
 * @property {number} User.LastLoginAt
 */
const UserProfileOut = {
  User: { // rqAuth.Users
    Id: 0, // uint64
    Email: '', // string
    Password: '', // string
    CreatedAt: 0, // int64
    CreatedBy: 0, // uint64
    UpdatedAt: 0, // int64
    UpdatedBy: 0, // uint64
    DeletedAt: 0, // int64
    PasswordSetAt: 0, // int64
    SecretCode: '', // string
    SecretCodeAt: 0, // int64
    VerificationSentAt: 0, // int64
    VerifiedAt: 0, // int64
    LastLoginAt: 0, // int64
  }, // rqAuth.Users
}
/**
 * @callback UserProfileCallback
 * @param {UserProfileOut} o
 * @returns {Promise}
 */
/**
 * @param  {UserProfileIn} i
 * @param {UserProfileCallback} cb
 * @returns {Promise}
 */
async function UserProfile( i, cb ) {
  return await axios.post( '/', i ).then( cb )
}


// Code generated by 1_codegen_test.go DO NOT EDIT.
